"""Cypher exporter for KnowHub knowledge artifacts."""

from __future__ import annotations

import json
import re
from typing import Any

from knowhub.schema import KnowledgeArtifact


def _quote(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _token(value: str, fallback: str) -> str:
    token = re.sub(r"[^A-Za-z0-9_]", "_", str(value or ""))
    token = re.sub(r"_+", "_", token).strip("_").upper()
    return token or fallback


def _properties(properties: dict[str, Any]) -> str:
    parts = []
    for key, value in sorted(properties.items()):
        prop_key = re.sub(r"[^A-Za-z0-9_]", "_", str(key)).strip("_")
        if not prop_key:
            continue
        if isinstance(value, (str, int, float, bool)) or value is None:
            rendered = _quote(value)
        else:
            rendered = _quote(json.dumps(value, ensure_ascii=False))
        parts.append(f"r.{prop_key} = {rendered}")
    return ", ".join(parts)


def render_cypher(artifacts: list[KnowledgeArtifact]) -> str:
    """Render artifacts as a portable Cypher script.

    The script is graph-ready but does not require direct Neo4j credentials.
    That makes it easy to inspect, commit, publish, or load later.
    """
    lines = [
        "// Generated by KnowHub",
        "CREATE CONSTRAINT knowhub_document_id IF NOT EXISTS FOR (d:Document) REQUIRE d.id IS UNIQUE;",
        "CREATE CONSTRAINT knowhub_entity_id IF NOT EXISTS FOR (e:KnowledgeEntity) REQUIRE e.id IS UNIQUE;",
        "",
    ]

    for artifact in artifacts:
        source = artifact.source
        lines.extend(
            [
                f"MERGE (d:Document {{id: {_quote(source.id)}}})",
                f"SET d.path = {_quote(source.path)}, d.title = {_quote(source.title)}, d.knowledge_type = {_quote(artifact.knowledge_type)}, d.reasoning = {_quote(artifact.reasoning)};",
                "",
            ]
        )

        for entity in artifact.entities:
            lines.extend(
                [
                    f"MERGE (e:KnowledgeEntity {{id: {_quote(entity.id)}}})",
                    f"SET e.name = {_quote(entity.name)}, e.type = {_quote(entity.type)}, e.properties_json = {_quote(json.dumps(entity.properties, ensure_ascii=False))}",
                    f"WITH e MATCH (d:Document {{id: {_quote(source.id)}}})",
                    "MERGE (d)-[:MENTIONS]->(e);",
                    "",
                ]
            )

        for relationship in artifact.relationships:
            rel_type = _token(relationship.relationship_type, "RELATES_TO")
            prop_clause = _properties(relationship.properties)
            set_parts = [
                f"r.source_document_id = {_quote(source.id)}",
                f"r.confirmed_by = {_quote(relationship.confirmed_by)}",
            ]
            if prop_clause:
                set_parts.append(prop_clause)

            lines.extend(
                [
                    f"MATCH (source:KnowledgeEntity {{id: {_quote(relationship.source_id)}}})",
                    f"MATCH (target:KnowledgeEntity {{id: {_quote(relationship.target_id)}}})",
                    f"MERGE (source)-[r:{rel_type}]->(target)",
                    f"SET {', '.join(set_parts)};",
                    "",
                ]
            )

        for index, gap in enumerate(artifact.knowledge_gaps, start=1):
            gap_id = f"{source.id}_gap_{index}"
            lines.extend(
                [
                    f"MERGE (g:KnowledgeGap {{id: {_quote(gap_id)}}})",
                    f"SET g.type = {_quote(gap.type)}, g.description = {_quote(gap.description)}, g.context = {_quote(gap.context)}",
                    f"WITH g MATCH (d:Document {{id: {_quote(source.id)}}})",
                    "MERGE (d)-[:HAS_GAP]->(g);",
                    "",
                ]
            )

    return "\n".join(lines).rstrip() + "\n"
